### ISSUE TITLE
OperationFuture returned by DocumentProcessorServiceClient.batchProcessDocumentsAsync() gets canceled before LRO completes

### ISSUE THREAD

**Issue by rmstar** [googleapis/java-document-ai#403]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
   General, Core, and Other are also allowed as types
2. OS type and version: linux
3. Java version: 8
4. documentai version(s): v1beta3

#### Steps to reproduce

This issue seems to happen when I send a batch of documents. I get a CancellationException after 4+ minutes, while the LRO is still being processed by the backend.

#### Code example

```java
      BatchProcessRequest request =
        BatchProcessRequest.newBuilder()
          .setName(name)
          .setInputDocuments(batchInputConfig)
          .setDocumentOutputConfig(outputConfig)
          .setSkipHumanReview(true)
          .build();

      OperationFuture<BatchProcessResponse, BatchProcessMetadata> future =
        client.batchProcessDocumentsAsync(request);
      LOG.info("Waiting for operation {} to complete...", future.getName());
      future.get(120, TimeUnit.MINUTES);
      LOG.info("Document processing complete.");

```

#### Stack trace
```
2021-04-08 19:27:08,130 - ERROR [Executor task launch worker for task 0:o.a.s.e.Executor@91] - Exception in task 0.0 in stage 0.0 (TID 0)
java.util.concurrent.CancellationException: Task was cancelled.
	at com.google.common.util.concurrent.AbstractFuture.cancellationExceptionWithCause(AbstractFuture.java:1112) ~[guava-13.0.1.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:498) ~[guava-13.0.1.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:401) ~[guava-13.0.1.jar:na]
	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83) ~[na:na]
	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:68) ~[guava-13.0.1.jar:na]
	at com.google.api.gax.longrunning.OperationFutureImpl.get(OperationFutureImpl.java:133) ~[na:na]
```

**Comment by Neenu1995** [comment]
Hi,
[This](https://github.com/googleapis/google-cloud-java#configuring-lro-timeouts) could be a possible workaround for the timeout issue. I will reach out to the service team about updating the timeout.

**Comment by rmstar** [comment]
@Neenu1995 can you please provide an example of how to set LRO timeout in the `DocumentProcessorServiceClient`?

**Comment by Neenu1995** [comment]
The work around is not setup in the Client Library code. The user would create their settings object and create their client with those settings. The implementation would look much similar to the work around mentioned.

**Comment by rmstar** [comment]
hm I tried this but it doesn't seem to work (task gets canceled before LRO finishes). Is this not the right way to set LRO timeout?

```
    DocumentProcessorServiceSettings.Builder settingsBuilder = DocumentProcessorServiceSettings.newBuilder();
    settingsBuilder
      .processDocumentSettings()
      .setRetrySettings(
        settingsBuilder
          .processDocumentSettings()
          .getRetrySettings()
          .toBuilder()
          .setTotalTimeout(Duration.ofMinutes(120)) // set LRO timeout to 2 hours
          .build());
    DocumentProcessorServiceSettings settings = settingsBuilder.build();

    try (DocumentProcessorServiceClient client = DocumentProcessorServiceClient.create(settings)) {      
        OperationFuture<BatchProcessResponse, BatchProcessMetadata> future = client.batchProcessDocumentsAsync(request);
       future.get(120, TimeUnit.MINUTES);
    }
  ```

**Comment by Neenu1995** [comment]
Can you try overriding the `batchProcessDocumentsOperationSettings()`?

**Comment by rmstar** [comment]
Thanks, that works!
```
    TimedRetryAlgorithm timedRetryAlgorithm = OperationTimedPollAlgorithm.create(
      RetrySettings.newBuilder()
        .setTotalTimeout(Duration.ofHours(2L))	// set polling timeout to 2 hours
        .build());
    DocumentProcessorServiceSettings.Builder settingsBuilder = DocumentProcessorServiceSettings.newBuilder();
    settingsBuilder
      .batchProcessDocumentsOperationSettings()
      .setPollingAlgorithm(timedRetryAlgorithm);
    DocumentProcessorServiceSettings settings = settingsBuilder.build();
    DocumentProcessorServiceClient client = DocumentProcessorServiceClient.create(settings);
```
